# Allow using debug dumps. It's not recommended on production servers.
debug: false
disabled-worlds:
  - nether_without_water
max-height: 999
min-height: 0
messages:
  permissions: "You do not have permission to do that!"
  config-reload: "Nether Water configuration reloaded!"
